UnifiedCore/UnifiedCore/AdminDashboard/routes.py
# imports
from flask import (render_template, request, Blueprint,
				   jsonify, url_for, redirect, flash)
from flask import current_app
from UnifiedCore.AdminDashboard.forms import (UploadVideoForm, UploadSampleQuestionPaper, DispatchNotification,
DispatchCircular, UploadNotes, UploadResults, UploadAttendance, UploadStudent)

# Register this Page as a Blueprint
admindashboard = Blueprint('admindashboard', __name__)

@admindashboard.route("/home")
def homepage():
	return render_template('main.html', title="Welcome", option="Home")

@admindashboard.route("/upload_video")
def upload_video():
	form = UploadVideoForm()
	return render_template('video.html', title="Upload Video", option="Upload Video", form=form)

@admindashboard.route("/upload_samplepaper")
def upload_samplepaper():
	form = UploadSampleQuestionPaper()
	return render_template('samplepaper.html', title="Upload Sample Paper", option="Upload Sample Question Paper", form=form)

@admindashboard.route("/dispatch_notification")
def dispatch_notification():
	form = DispatchNotification()
	return render_template('notification.html', title="Send Notification", option="Dispatch Notification", form=form)

@admindashboard.route("/dispatch_circular")
def dispatch_circular():
	form = DispatchCircular()
	return render_template('circular.html', title="Send Circular", option="Dispatch Circular", form=form)

@admindashboard.route("/upload_notes")
def upload_notes():
	form = UploadNotes()
	return render_template('notes.html', title="Upload Notes", option=" Upload Notes", form=form)

@admindashboard.route("/upload_results")
def upload_results():
	form = UploadResults()
	return render_template('results.html', title="Upload Results", option=" Upload Results", form=form)


@admindashboard.route("/upload_attendance")
def upload_attendance():
	form = UploadAttendance()
	return render_template('attendance.html', title="Upload Attendance", option=" Upload Attendance", form=form)

@admindashboard.route("/upload_student_user")
def upload_student_user():
	form = UploadStudent()
	return render_template('createstudentuser.html', title="Upload Users", option="Import Users", form=form)

UnifiedCore/UnifiedCore/Main/routes.py
# imports
from flask import (render_template,request, Blueprint,
				   jsonify, url_for, redirect, flash)
from flask import current_app

# Register this Page as a Blueprint
main = Blueprint('main', __name__)

@main.route("/")
def splashscreen():
	return render_template('splashscreen.html')

UnifiedCore/UnifiedCore/templates/attendance.html
{% extends 'layout.html' %}
{% block content %}  
<link rel="stylesheet" href="{{url_for('static', filename='CSS/results.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='CSS/formcontrol.css')}}">
<form action="{{url_for('attendance.upload_attendance')}}" method="post" enctype="multipart/form-data" class="frm">
{{ form.hidden_tag()}}
<h3></h3>
<div class="flexible">
<h2>Upload Attendance Data File </h2>
{{form.submit(class='sbutton')}}
</div>
<div class="mainsection">
    <h3>Academic Year</h3>
    {{form.year(class='form-control', placeholder='Academic Year')}} 
    <h3>Browse DataFile</h3>
    {{form.file()}} 
</div>
</form>
{% endblock content %}

UnifiedCore/UnifiedCore/templates/circular.html
{% extends 'layout.html' %}
{% block content %}  

<link rel="stylesheet" href="{{url_for('static', filename='CSS/reminder.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='CSS/formcontrol.css')}}">
<form action="{{url_for('alerts.create_circular')}}" method="post" enctype="multipart/form-data" class="frm">
{{ form.hidden_tag()}}
<div class="flexible">
    <h2>Dispatch Circular</h2>
    {{form.submit(class='sbutton')}} 
</div>
<div class="mainsection">
    <h4>Circular Title</h4> 
    {{ form.title(class="form-control", placeholder="Circular Title") }}
    <br>
    <h4>Circular File</h4>
    {{ form.file() }}
    <h4>Target Grade</h4>
    {{ form.grade(class="form-control") }}
    <br>
    <h4>Circular Body</h4>
    {{ form.message(class="form-control", rows="20", cols="10", placeholder="Circular Body") }}

</div>
</form>
{% endblock content %}

UnifiedCore/UnifiedCore/templates/createstudentuser.html
{% extends 'layout.html' %}
{% block content %}  
<link rel="stylesheet" href="{{url_for('static', filename='CSS/results.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='CSS/formcontrol.css')}}">
<form action="{{url_for('students.create_student_user')}}" method="post" enctype="multipart/form-data" class="frm">
{{ form.hidden_tag()}}
<h3></h3>
<div class="flexible">
<h2>Upload Student Data File </h2>
{{form.submit(class='sbutton')}}
</div>
<div class="mainsection">
    <h3>Browse DataFile</h3>
    {{form.file()}} 
</div>
</form>
{% endblock content %}

UnifiedCore/UnifiedCore/templates/layout.html
<!doctype html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
      <title>{{title}}</title>
      <!-- Add to homescreen for Chrome on Android -->
      <meta name="mobile-web-app-capable" content="yes">
      <link rel="icon" sizes="192x192" href="images/android-desktop.png">
      <!-- Add to homescreen for Safari on iOS -->
      <meta name="apple-mobile-web-app-capable" content="yes">
      <meta name="apple-mobile-web-app-status-bar-style" content="black">
      <meta name="apple-mobile-web-app-title" content="Material Design Lite">
      <link rel="apple-touch-icon-precomposed" href="images/ios-desktop.png">
      <!-- Tile icon for Win8 (144x144 + tile color) -->
      <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
      <meta name="msapplication-TileColor" content="#3372DF">
      <link rel="shortcut icon" href="images/favicon.png">
      <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
      <!--
         <link rel="canonical" href="http://www.example.com/">
         -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
      <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.cyan-light_blue.min.css">
      <link rel="stylesheet" href="{{url_for('static', filename='CSS/layout.css')}}">
            <!--Bootstrap-->

      <style>
         #view-source {
         position: fixed;
         display: block;
         right: 0;
         bottom: 0;
         margin-right: 40px;
         margin-bottom: 40px;
         z-index: 900;
         color: rgb(255, 255, 255);
         background-color: rgb(22, 46, 77);
         }
      </style>
	  <!--Prevent Mobile Running-->
      <script>
         (function (a, b) {
         if (/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test(a) || /1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0, 4))) window.location = b
         })(navigator.userAgent || navigator.vendor || window.opera, 'localhost/home');
      </script>
   </head>
   <body>
      <!--Header-->
      <div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
         <header class="demo-header mdl-layout__header dark mdl-color-text--grey-50">
            <div class="mdl-layout__header-row">
               <span class="mdl-layout-title mainheader">St Paul's English School <span class="angle-seperator">></span> {{option}}</span>
               <div class="mdl-layout-spacer"></div>
               <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
                  <label class="mdl-button mdl-js-button mdl-button--icon" for="search">
                  <i class="material-icons">search</i>	
                  </label>
                  <div class="mdl-textfield__expandable-holder">
                     <input class="mdl-textfield__input" type="text" id="search">
                     <label class="mdl-textfield__label" for="search">Enter your query...</label>
                  </div>
               </div>
            
			   <img src="{{url_for('static', filename='Icons/femaleicon.png')}}" class="demo-avatar mx-3">
			   <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="hdrbtn">
			   <i class="material-icons">more_vert</i>
               </button>
               <ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="hdrbtn">
                  <li class="mdl-menu__item">Log Out</li>
                  <li class="mdl-menu__item">Contact</li>
                  <li class="mdl-menu__item">About</li>
               </ul>
            </div>
         </header>
         <!--Sidebar-->
         <div class="demo-drawer mdl-layout__drawer schoolcolor mdl-color-text--grey-50">
            <!--SideBar Header-->
            <header class="demo-drawer-header">
               <!--
                  <img src="{{url_for('static', filename='Icons/models.png')}}" class="demo-avatar">
                             <div class="demo-avatar-dropdown">
                                <span>St Pauls English School</span>
                  	<div class="mdl-layout-spacer"></div>
                                <button id="accbtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
                                <i class="material-icons" role="presentation">arrow_drop_down</i>
                                <span class="visuallyhidden">Accounts</span>
                                </button>
                                <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="accbtn">
                                   <li class="mdl-menu__item">Manas Hejmadi</li>
                                   <li class="mdl-menu__item">Manas 2</li>
                                   <li class="mdl-menu__item"><i class="material-icons">add</i>Add another account...</li>
                                </ul>
                             </div>
                    -->
               <center>
			   <a href="{{url_for('admindashboard.homepage')}}"><img src="{{url_for('static', filename='Images/logo.png')}}" alt="" class="logo"></a>
			   </center>
            </header>
            <!--Sidebar Body-->
            <nav class="demo-navigation mdl-navigation dark">
               <a class="mdl-navigation__link" href="{{url_for('admindashboard.upload_video')}}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">videocam</i>Upload Video</a>
               <a class="mdl-navigation__link" href="{{url_for('admindashboard.upload_samplepaper')}}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">attachment</i>Sample Papers</a>
               <a class="mdl-navigation__link" href="{{url_for('admindashboard.upload_notes')}}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">import_contacts</i>Upload Notes</a>
               <a class="mdl-navigation__link" href="{{url_for('admindashboard.upload_attendance')}}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">how_to_reg</i>Attendance</a>
               <a class="mdl-navigation__link" href="{{url_for('admindashboard.dispatch_circular')}}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">info</i>Circulars</a>
               <a class="mdl-navigation__link" href="{{url_for('admindashboard.dispatch_notification')}}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">notifications_active</i>Notifications</a>
               <a class="mdl-navigation__link" href="{{url_for('admindashboard.upload_results')}}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">bar_chart</i>Results</a>
               <a class="mdl-navigation__link" href="{{url_for('admindashboard.upload_student_user')}}"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">person_add</i>Add Students</a>
            </nav>
         </div>
		 
         <!--Main Body-->

          <main class="mdl-layout__content">
          <div class="container">
           {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }} flashmessage" style="width:890px;">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          <br>
         {% block content %}
            {% endblock content %}
          </div>
            
			<img src="{{url_for('static', filename='Images/logo.svg')}}" alt="" class="logo_watermark">
         </main>
         
        
		 
      </div>
      <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect " id="view-source">
      <i class="material-icons">add</i>
      </button>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
   </body>
</html>


UnifiedCore/UnifiedCore/templates/main.html
{% extends 'layout.html' %}
{% block content %}  
<link rel="stylesheet" href="{{url_for('static', filename='CSS/main.css')}}">
<img src="{{url_for('static', filename='Images/x.png')}}" alt="" class="welcome">
<h1>Welcome to the School Companion Web Console.</h1>
{% endblock content %}

UnifiedCore/UnifiedCore/templates/notes.html
{% extends 'layout.html' %}
{% block content %}  

<link rel="stylesheet" href="{{url_for('static', filename='CSS/notes.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='CSS/formcontrol.css')}}">
<form action="{{url_for('notes.upload_notes')}}" method="post" enctype="multipart/form-data" class="frm">
{{ form.hidden_tag()}}
<div class="flexible">
<h2>Upload Notes</h2>
{{form.submit(class='sbutton')}} 
</div>
<div class="flexible">
    <div class="part form-group">
        <h4>Notes Name</h4>
        {{ form.notes_name(class="form-control", placeholder="Notes Name") }}
        <h4>Topic</h4>
        {{ form.topic(class="form-control", placeholder="Topic") }}
        <h4>Subject</h4>
        {{ form.subject(class="form-control") }}
        <h4>Grade</h4>
        {{ form.grade(class="form-control") }}
    </div>

    <div class="part lpart form-group">
        <h4>Notes File</h4>
        {{ form.file() }}
    </div>
<div>
</form>
{% endblock content %}

UnifiedCore/UnifiedCore/templates/notification.html
{% extends 'layout.html' %}
{% block content %}  

<link rel="stylesheet" href="{{url_for('static', filename='CSS/notification.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='CSS/formcontrol.css')}}">
<form action="{{url_for('alerts.create_notification')}}" method="post" enctype="multipart/form-data" class="frm">
{{ form.hidden_tag()}}
<div class="flexible">
    <h2>Dispatch Notification</h2>
    {{form.submit(class='sbutton')}} 
</div>
<div class="mainsection">
    <h4>Notification Title</h4>
    {{ form.title(class="form-control", placeholder="Notification Title") }}
    <br>
    <h4>Target Grade</h4>
    {{ form.grade(class="form-control") }}
    <br>
    <h4>Notification Body</h4>
    {{ form.message(class="form-control", rows="20", cols="10", placeholder="Notification Body") }}
</div>
</form>
{% endblock content %}

UnifiedCore/UnifiedCore/templates/results.html
{% extends 'layout.html' %}
{% block content %}  
<link rel="stylesheet" href="{{url_for('static', filename='CSS/results.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='CSS/formcontrol.css')}}">
<form action="{{url_for('results.upload_results')}}" method="post" enctype="multipart/form-data" class="frm">
{{ form.hidden_tag()}}
<h3></h3>
<div class="flexible">
<h2>Upload Result Data File </h2>
{{form.submit(class='sbutton')}}
</div>
<div class="mainsection">
    <h3>Term Name</h3>
    {{form.term_name(class='form-control', placeholder='School Term Name')}} 
    <h3>Academic Year</h3>
    {{form.year(class='form-control', placeholder='Academic Year')}} 
    <h3>Browse DataFile</h3>
    {{form.file()}} 
</div>
</form>
{% endblock content %}

UnifiedCore/UnifiedCore/templates/samplepaper.html
{% extends 'layout.html' %}
{% block content %}  

<link rel="stylesheet" href="{{url_for('static', filename='CSS/video.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='CSS/formcontrol.css')}}">
<form action="{{url_for('samplepapers.upload_sample_paper')}}" method="post" enctype="multipart/form-data" class="frm">
{{ form.hidden_tag()}}
<div class="flexible">
<h2>Upload Sample Question Paper</h2>
{{form.submit(class='sbutton')}} 

</div>
<div class="flexible">
    <div class="part form-group">
        <h4>QuestionPaper Name</h4>
        {{ form.paper_name(class="form-control", placeholder="Question Paper Name") }}
        <h4>Subject</h4>
        {{ form.subject(class="form-control") }}
        <h4>Grade</h4>
        {{ form.grade(class="form-control") }}
    </div>

    <div class="part lpart form-group">
        <h4>Question Paper Year</h4>
        {{ form.year(class="form-control", placeholder="QuestionPaper Year")}}
        <br>
        <h4>Question Paper File</h4>
        {{ form.file() }}
    </div>
<div>
</form>
{% endblock content %}

UnifiedCore/UnifiedCore/templates/splashscreen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Web Console</title>
    <link rel="stylesheet" href="{{url_for('static', filename='CSS/splashscreen.css')}}">
    <script>
        window.onload = function() {
            setTimeout(()=> window.location = "{{url_for('admindashboard.homepage')}}", 5000);
        }
    </script>
</head>
<body>
        <img src="{{url_for('static', filename='Images/logo.svg')}}" alt="" class="logo">
</body>
</html>

UnifiedCore/UnifiedCore/templates/video.html
{% extends 'layout.html' %}
{% block content %}  

<link rel="stylesheet" href="{{url_for('static', filename='CSS/video.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='CSS/formcontrol.css')}}">
<form action="{{url_for('videos.upload_video')}}" method="post" enctype="multipart/form-data" class="frm">
{{ form.hidden_tag()}}
<div class="flexible">
<h2>Upload Video</h2>
{{form.submit(class='sbutton')}} 

</div>
<div class="flexible">
    <div class="part form-group">
        <h4>Video Name</h4>
        {{ form.vid_name(class="form-control", placeholder="Video Name") }}
        <h4>Topic</h4>
        {{ form.topic(class="form-control", placeholder="Topic") }}
        <h4>Subject</h4>
        {{ form.subject(class="form-control") }}
        <h4>Grade</h4>
        {{ form.grade(class="form-control") }}
    </div>
    

    <div class="part lpart form-group">
        <h4>Description</h4>
        {{ form.description(class="form-control", rows = "7", cols= "25", placeholder="Description")}}
        <br>
        <h4>Video File</h4>
        {{ form.file() }}
        <h4>Thumbnail</h4>
        {{ form.thumbnail() }}
    </div>
<div>
</form>
{% endblock content %}